// MicrophoneController
// Board: nullbits Bit-C PRO (ATmega32U4)
// Select "Arduino Leonardo" in the Arduino IDE board menu.
//
// Required libraries:
//   - Keyboard  (built-in)
//   - Joystick  by Matthew Heironimus (install via Library Manager)
//
// Behavior:
//   KEYBOARD mode (switch LOW):
//     Tap  → toggle mic (press + release key; LED reflects toggle state)
//     Hold → push-to-talk (key held until released; LED on while held)
//   GAMEPAD mode (switch HIGH):
//     Hold → joystick button held (LED on while held)
//     Tap  → brief joystick button press
//
// Wiring:
//   BTN1 → pin 2 (to GND, uses internal pull-up)
//   BTN2 → pin 3 (to GND, uses internal pull-up)
//   LED1 → pin 4 (through ~220Ω resistor to GND)
//   LED2 → pin 5 (through ~220Ω resistor to GND)
//   MODE → pin 6 (switch to GND = keyboard mode; open/HIGH = gamepad mode)

#include <Keyboard.h>
#include <Joystick.h>

// --- Pins ---
const uint8_t BTN_PINS[2] = { 2, 3 };
const uint8_t LED_PINS[2] = { 4, 5 };
const uint8_t MODE_PIN    = 6;

// --- Keys sent in keyboard mode ---
// Scroll Lock and F24 are chosen deliberately:
//   • Scroll Lock:  vestigial key present on virtually all keyboards; no game
//                   engine binds it by default; supported by Discord, TeamSpeak,
//                   and Mumble for PTT.
//   • F24:          highest function key; only generated by specialty hardware
//                   (like this controller) so it can never be accidentally
//                   triggered from a standard keyboard; recognized by all modern
//                   game engines and VoIP apps.
// Both keys are absent from default gameplay configurations in every major
// title while remaining fully bindable in-game and in comms software.
#ifndef KEY_SCROLL_LOCK
  #define KEY_SCROLL_LOCK 0xCF
#endif
#ifndef KEY_F24
  #define KEY_F24 0xFB
#endif
const uint8_t MIC_KEYS[2] = { KEY_SCROLL_LOCK, KEY_F24 };

// --- Timing ---
const unsigned long HOLD_MS     = 300;  // ms to distinguish tap from hold
const unsigned long DEBOUNCE_MS = 20;

// --- Joystick ---
// Declared with 32 buttons so the two active buttons land at indices 19 and 20
// (reported to games as buttons 20 and 21).  The highest button count of any
// current standard or elite controller over USB HID is 14 (DualSense); Xbox
// Elite Series 2 back paddles remap to existing button slots rather than adding
// new indices.  Buttons 20-21 are therefore safely beyond all shipping hardware.
const uint8_t JOY_BTN[2] = { 19, 20 }; // 0-indexed; games see 20 and 21

Joystick_ Joystick(
  JOYSTICK_DEFAULT_REPORT_ID,
  JOYSTICK_TYPE_GAMEPAD,
  32, 0,                            // 32 buttons declared, 0 hat switches
  false, false, false,              // no X/Y/Z axes
  false, false, false,              // no Rx/Ry/Rz
  false, false, false, false, false // no extra axes
);

enum Mode { KEYBOARD_MODE, GAMEPAD_MODE };
Mode currentMode;

struct Button {
  bool lastRaw          = true;  // HIGH = not pressed (pull-up)
  bool pressed          = false;
  bool holdFired        = false;
  bool toggleState      = false; // keyboard mode: is mic currently "on"?
  unsigned long pressStart    = 0;
  unsigned long lastDebounce  = 0;
};

Button buttons[2];

// ---------------------------------------------------------------------------

void setup() {
  for (int i = 0; i < 2; i++) {
    pinMode(BTN_PINS[i], INPUT_PULLUP);
    pinMode(LED_PINS[i], OUTPUT);
    digitalWrite(LED_PINS[i], LOW);
  }
  pinMode(MODE_PIN, INPUT_PULLUP);

  Joystick.begin(false); // false = manual sendState()
  Keyboard.begin();

  currentMode = readMode();
}

void loop() {
  // Handle mode switch changes
  Mode newMode = readMode();
  if (newMode != currentMode) {
    releaseAll();
    currentMode = newMode;
  }

  for (int i = 0; i < 2; i++) {
    handleButton(i);
  }

  Joystick.sendState();
}

// ---------------------------------------------------------------------------

Mode readMode() {
  return (digitalRead(MODE_PIN) == LOW) ? KEYBOARD_MODE : GAMEPAD_MODE;
}

void handleButton(int idx) {
  Button& btn     = buttons[idx];
  bool raw        = (digitalRead(BTN_PINS[idx]) == LOW);
  unsigned long now = millis();

  // Debounce: ignore changes shorter than DEBOUNCE_MS
  if (raw != btn.lastRaw) {
    btn.lastDebounce = now;
    btn.lastRaw = raw;
  }
  if ((now - btn.lastDebounce) < DEBOUNCE_MS) return;

  bool wasPressed = btn.pressed;

  // ── Press start ──────────────────────────────────────────────────────────
  if (!wasPressed && raw) {
    btn.pressed    = true;
    btn.pressStart = now;
    btn.holdFired  = false;

    if (currentMode == GAMEPAD_MODE) {
      Joystick.setButton(JOY_BTN[idx], 1);
    }
  }

  // ── Hold threshold reached ───────────────────────────────────────────────
  if (btn.pressed && !btn.holdFired && (now - btn.pressStart >= HOLD_MS)) {
    btn.holdFired = true;
    if (currentMode == KEYBOARD_MODE) {
      Keyboard.press(MIC_KEYS[idx]); // PTT: hold key down
    }
  }

  // ── Release ──────────────────────────────────────────────────────────────
  if (wasPressed && !raw) {
    btn.pressed = false;

    if (currentMode == KEYBOARD_MODE) {
      if (btn.holdFired) {
        Keyboard.release(MIC_KEYS[idx]); // end PTT
      } else {
        // Tap: toggle mic state
        btn.toggleState = !btn.toggleState;
        Keyboard.press(MIC_KEYS[idx]);
        delay(30);
        Keyboard.release(MIC_KEYS[idx]);
      }
    } else {
      Joystick.setButton(JOY_BTN[idx], 0);
    }

    btn.holdFired = false;
  }

  // ── LED ──────────────────────────────────────────────────────────────────
  bool ledOn;
  if (currentMode == KEYBOARD_MODE) {
    // On when mic is toggled on, or while PTT hold is active
    ledOn = btn.toggleState || (btn.pressed && btn.holdFired);
  } else {
    ledOn = btn.pressed;
  }
  digitalWrite(LED_PINS[idx], ledOn ? HIGH : LOW);
}

void releaseAll() {
  Keyboard.releaseAll();
  for (int i = 0; i < 2; i++) {
    Joystick.setButton(JOY_BTN[i], 0);
    buttons[i].pressed      = false;
    buttons[i].holdFired    = false;
    buttons[i].toggleState  = false;
    digitalWrite(LED_PINS[i], LOW);
  }
  Joystick.sendState();
}
